export const listOrder=[
    {
        order_id:1,
        user_id:"quyetvosy@g,ail.com",
        order_at:new Date,
        total_price:1000000,
        status:"mới đặt hàng",
        note:"ghi chú",
        order_details:[],
        created_at: new Date,
        updated_at:new Date,
    },
    {
        order_id:2,
        user_id:"quyetvosy@g,ail.com",
        order_at:new Date,
        total_price:1000000,
        status:"mới đặt hàng",
        note:"ghi chú",
        order_details:[],
        created_at: new Date,
        updated_at:new Date,
    },
    {
        order_id:3,
        user_id:"quyetvosy@g,ail.com",
        order_at:new Date,
        total_price:1000000,
        status:"mới đặt hàng",
        note:"ghi chú",
        order_details:[],
        created_at: new Date,
        updated_at:new Date,
    },
    {
        order_id:4,
        user_id:"quyetvosy@g,ail.com",
        order_at:new Date,
        total_price:1000000,
        status:"đang vận chuyển",
        note:"ghi chú",
        order_details:[],
        created_at: new Date,
        updated_at:new Date,
    },
]