export const users = [
  {
    id: 1,
    name: "Quyết",
    email: "quyetvosy@gmail.com",
    phone: "0911639333",
    password: "111",
    repeatPassword: "111",
    created_at: new Date,
    avatar: "string",
    cart:[],
    role: "customer",
    status: "activate",
    address:"Đà Nẵng"
  },
  {
    id: 2,
    name: "Thái",
    email: "quyetvosy@gmail.com",
    phone: "0911639333",
    password: "111",
    repeatPassword: "111",
    created_at: new Date,
    avatar: "string",
    cart:[],
    role: "customer",
    status: "activate",
    address:"Hải Phòng"
  },
  {
    id: 3,
    name: "Viễn",
    email: "quyetvosy@gmail.com",
    phone: "0911639333",
    password: "111",
    repeatPassword: "111",
    created_at: new Date,
    avatar: "string",
    cart:[],
    role: "customer",
    status: "activate",
    address:"Đà Nẵng"
  },
  {
    id: 4,
    name: "Hương",
    email: "quyetvosy@gmail.com",
    phone: "0911639333",
    password: "111",
    repeatPassword: "111",
    created_at: new Date,
    avatar: "string",
    cart:[],
    role: "customer",
    status: "activate",
    address:"Hà Nội"
  },
];
